analyze:
  stage: analyze
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/node:latest
  allow_failure: true
  needs:
    - test
  only:
    - dev
  environment:
    name: dev
  script:
    - npm install -g sonarqube-scanner
    - >
      sonar-scanner
      -Dsonar.projectKey=${SONAR_PROJECT_KEY}
      -Dsonar.host.url=${SONAR_HOST_URL}
      -Dsonar.login=${SONAR_LOGIN}
      -Dsonar.organization=inside-sistemas
      -Dsonar.projectName=EuGestor-Reports-Frontend
      -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      -Dsonar.sourceEncoding=UTF-8
      -Dsonar.sources=src/app
      -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
      -Dsonar.tests=src/app
      -Dsonar.test.inclusions=**/*.spec.ts
