test:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/trion/ng-cli-karma:latest
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
  needs:
    - dependencies
  script:
    - ng test --progress false --watch=false --code-coverage
  artifacts:
    when: always
    paths:
      - ./coverage
    reports:
      junit:
        - ./coverage/junit.xml
